import type { NextPage } from 'next'
import Head from 'next/head'
import Welcome from '../components/Welcome'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Next.js Typescript Chakra-UI starter</title>
				<meta
					name='description'
					content='Generated by next-typescript-chakra-ui-starter'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Welcome />
			</main>
		</div>
	)
}

export default Home
